"""Novo atributo da tabela users (url da foto de perfil)

Revision ID: 262f02a4502d
Revises: 5da9909f9718
Create Date: 2026-03-19 10:47:32.209987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262f02a4502d'
down_revision: Union[str, Sequence[str], None] = '5da9909f9718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
