"""Mudança no nome das chaves estrangeiras

Revision ID: 46bdd7fb1d35
Revises: 5e5fa0af99c2
Create Date: 2026-04-10 18:52:54.794735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bdd7fb1d35'
down_revision: Union[str, Sequence[str], None] = '5e5fa0af99c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('answers_questions_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.drop_column('answers', 'questions_id')
    op.add_column('comments', sa.Column('analysis_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('comments_analyses_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'analyses_id')
    op.add_column('reports', sa.Column('analysis_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('reports_analyses_id_key'), 'reports', type_='unique')
    op.create_unique_constraint(None, 'reports', ['analysis_id'])
    op.drop_constraint(op.f('reports_analyses_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reports', 'analyses_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('analyses_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_analyses_id_fkey'), 'reports', 'analyses', ['analyses_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'reports', type_='unique')
    op.create_unique_constraint(op.f('reports_analyses_id_key'), 'reports', ['analyses_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('reports', 'analysis_id')
    op.add_column('comments', sa.Column('analyses_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_analyses_id_fkey'), 'comments', 'analyses', ['analyses_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'analysis_id')
    op.add_column('answers', sa.Column('questions_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_questions_id_fkey'), 'answers', 'questions', ['questions_id'], ['id'])
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
