"""Novo atributo para persistir a quantidade de comentários processados

Revision ID: 47ee8309d912
Revises: aef0d7ec2199
Create Date: 2026-10-04 21:33:32.126965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ee8309d912'
down_revision: Union[str, Sequence[str], None] = 'aef0d7ec2199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('processed_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'processed_comments')
    # ### end Alembic commands ###
