"""Campos UUID agora com tipo de dado UUID

Revision ID: 4dfd9536064b
Revises: e5fc2b180b97
Create Date: 2026-03-27 20:25:59.668656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfd9536064b'
down_revision: Union[str, Sequence[str], None] = 'e5fc2b180b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
