"""Dois novos atributos (terms_accepted e email verified) na tabela users

Revision ID: 5e5fa0af99c2
Revises: 4dfd9536064b
Create Date: 2026-04-08 10:37:30.103973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5fa0af99c2'
down_revision: Union[str, Sequence[str], None] = '4dfd9536064b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_analyses_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'analyses', ['analyses_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reports_analyses_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'analyses', ['analyses_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'terms_accepted')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_analyses_id_fkey'), 'reports', 'analyses', ['analyses_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_analyses_id_fkey'), 'comments', 'analyses', ['analyses_id'], ['id'])
    # ### end Alembic commands ###
