"""Adicionado soft delete nos relatorios

Revision ID: 8250804524c5
Revises: d32a4fc4fe2b
Create Date: 2026-10-07 08:31:47.921157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8250804524c5'
down_revision: Union[str, Sequence[str], None] = 'd32a4fc4fe2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'deleted_at')
    # ### end Alembic commands ###
