"""On update no campo fineshed_at na tabela analises

Revision ID: 96027d099feb
Revises: cf80448a6699
Create Date: 2026-05-21 10:05:51.463607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96027d099feb'
down_revision: Union[str, Sequence[str], None] = 'cf80448a6699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
