"""Novos atributos na tabela oauth para controlar o ciclo de vida dos tokens

Revision ID: aef0d7ec2199
Revises: 12fc794095d4
Create Date: 2026-08-13 23:42:51.207487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef0d7ec2199'
down_revision: Union[str, Sequence[str], None] = '12fc794095d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauths', sa.Column('expires_in', sa.DateTime(timezone=True), nullable=False))
    op.add_column('oauths', sa.Column('refresh_token_expires_in', sa.DateTime(timezone=True), nullable=False))
    op.add_column('oauths', sa.Column('scope', sa.String(), nullable=False))
    op.add_column('oauths', sa.Column('token_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauths', 'token_type')
    op.drop_column('oauths', 'scope')
    op.drop_column('oauths', 'refresh_token_expires_in')
    op.drop_column('oauths', 'expires_in')
    # ### end Alembic commands ###
