"""Atributos nulos na tabela reports (prompt, report_markdown, report_title)

Revision ID: cf80448a6699
Revises: 46bdd7fb1d35
Create Date: 2026-04-15 22:10:43.637867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf80448a6699'
down_revision: Union[str, Sequence[str], None] = '46bdd7fb1d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'report_markdown',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'report_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'report_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'report_markdown',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reports', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
