"""Atributos updated_at nas tabelas e remoção do atributo image_url de users

Revision ID: e5fc2b180b97
Revises: 262f02a4502d
Create Date: 2026-03-26 21:35:41.842214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fc2b180b97'
down_revision: Union[str, Sequence[str], None] = '262f02a4502d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('users_image_url_key'), 'users', type_='unique')
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_image_url_key'), 'users', ['image_url'], postgresql_nulls_not_distinct=False)
    op.drop_column('reports', 'updated_at')
    op.drop_column('answers', 'updated_at')
    # ### end Alembic commands ###
