"""Removendo atributos de input e output tokens e renomeando os nomes dos atributos de comentários

Revision ID: ff4a5d6f067d
Revises: 8250804524c5
Create Date: 2026-10-07 21:57:36.486926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4a5d6f067d'
down_revision: Union[str, Sequence[str], None] = '8250804524c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('comments_processed', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('comments_positive', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('comments_negative', sa.Integer(), nullable=True))
    op.drop_column('reports', 'processed_comments_negative')
    op.drop_column('reports', 'processed_comments')
    op.drop_column('reports', 'processed_comments_positive')
    op.drop_column('reports', 'output_tokens')
    op.drop_column('reports', 'input_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('processed_comments_positive', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('processed_comments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('processed_comments_negative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'comments_negative')
    op.drop_column('reports', 'comments_positive')
    op.drop_column('reports', 'comments_processed')
    # ### end Alembic commands ###
